nome = input('Digite o nome do cliente: ')
diav = input('Digite o dia de vencimento: ')
mesv = input('Digite o mês de vencimento: ')
valor = input('Digite o valor da fatura: ')
print(f'Olá, {nome}')
print(f'A sua fatura com vencimento em {diav} de {mesv} no valor de R$ {valor} está fechada.')
